"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef } from "react";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { LoaderCircle } from "lucide-react";
import axios from "axios";
import MobileHeader from "@/components/layout/MobileHeader";
import { LocationButton } from "@/features/location";
import { useHydrated } from "@/lib/use-hydrated";
import { useAppSelector } from "@/store/hooks";
import { getBusinessNameBySlug, getNearbyOffers } from "../business.service";
import type { NearbyOffer } from "../business.types";

export function NearbyOffersPage() {
  const hydrated = useHydrated();
  const { lat, lng, locality, city } = useAppSelector((state) => state.location);
  const query = useInfiniteQuery({ queryKey: ["nearby-offers", lat, lng], queryFn: ({ pageParam }) => getNearbyOffers({ lat: lat!, lng: lng!, page: pageParam }), initialPageParam: 1, getNextPageParam: (page) => page.pagination.has_next ? page.pagination.page + 1 : undefined, enabled: hydrated && lat !== null && lng !== null });
  const offers = useMemo(() => query.data?.pages.flatMap((page) => page.results) ?? [], [query.data]);
  const loadMoreRef = useRef<HTMLDivElement>(null);
  const { fetchNextPage, hasNextPage, isFetchingNextPage } = query;
  useEffect(() => { const target = loadMoreRef.current; if (!target) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && hasNextPage && !isFetchingNextPage) void fetchNextPage(); }, { rootMargin: "300px" }); observer.observe(target); return () => observer.disconnect(); }, [fetchNextPage, hasNextPage, isFetchingNextPage]);
  const error = axios.isAxiosError(query.error) ? query.error.response?.data?.detail ?? query.error.message : "Unable to load nearby offers.";
  return <div className="min-h-dvh bg-slate-50 pb-10"><MobileHeader title="Offers" subtitle={locality && city ? `Near ${locality}, ${city}` : "Offers near you"} /><main className="mx-auto w-full max-w-3xl px-page pt-5">{!hydrated ? <OfferSkeleton /> : lat === null || lng === null ? <div className="rounded-2xl border border-slate-100 bg-white p-7 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-brand-50 text-brand"><i className="fa-solid fa-location-dot" /></span><h2 className="mt-3 text-sm font-extrabold">Choose your location</h2><p className="mt-1 text-xs text-foreground-muted">Select an area to discover offers near you.</p><LocationButton className="mt-4 rounded-xl bg-brand px-5 py-2.5 text-sm font-bold text-white">Choose location</LocationButton></div> : query.isPending ? <OfferSkeleton /> : query.isError ? <div role="alert" className="rounded-2xl bg-red-50 p-5 text-center text-sm text-danger"><p>{String(error)}</p><button type="button" onClick={() => void query.refetch()} className="mt-3 font-extrabold underline">Try again</button></div> : offers.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center"><i className="fa-solid fa-tags text-2xl text-brand" /><h2 className="mt-3 text-sm font-extrabold">No nearby offers</h2><p className="mt-1 text-xs text-foreground-muted">Check again later for new deals.</p></div> : <div className="space-y-4">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div>}<div ref={loadMoreRef} className="flex h-20 items-center justify-center" aria-live="polite">{query.isFetchingNextPage && <><LoaderCircle size={20} className="animate-spin text-brand" /><span className="ml-2 text-sm font-semibold text-foreground-muted">Loading more</span></>}{!query.hasNextPage && offers.length > 0 && <span className="text-xs font-semibold text-foreground-subtle">You&apos;ve reached the end</span>}</div></main></div>;
}

function OfferCard({ offer }: { offer: NearbyOffer }) {
  const businessHref = `/business/${encodeURIComponent(offer.business.slug)}`;
  const businessQuery = useQuery({ queryKey: ["business", "offer-card", offer.business.slug], queryFn: () => getBusinessNameBySlug(offer.business.slug) });
  const business = businessQuery.data;
  const coordinates = business?.location.coordinates;
  const address = business ? [business.location.address, business.location.landmark, business.location.locality, business.location.city.name, business.location.city.state, business.location.postal_code].filter(Boolean).join(", ") : `${offer.business.locality}, ${offer.business.city.name}`;
  const directionsHref = coordinates && Number.isFinite(coordinates.latitude) && Number.isFinite(coordinates.longitude) ? `https://www.google.com/maps/dir/?api=1&destination=${coordinates.latitude},${coordinates.longitude}` : undefined;
  return <article className="overflow-hidden rounded-2xl border border-slate-100 bg-white p-4 shadow-[0_3px_12px_rgba(15,23,42,0.05)]"><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand"><i className="fa-solid fa-tag" /></span><h2 className="min-w-0 flex-1 text-lg font-extrabold">{offer.title}</h2></div><p className="mt-2 text-sm leading-5 text-foreground-muted">{offer.description}</p>{offer.terms.length > 0 && <ul className="mt-3 space-y-1.5">{offer.terms.slice(0, 2).map((term, index) => <li key={index} className="flex gap-2 text-xs text-foreground-muted"><i className="fa-solid fa-check mt-0.5 text-[10px] text-brand" />{term}</li>)}</ul>}<div className="mb-2 mt-4 space-y-1 text-xs font-extrabold text-brand"><p><i className="fa-solid fa-calendar-day mr-1.5" />Starts on {formatDate(offer.starts_at)}</p><p><i className="fa-solid fa-calendar-check mr-1.5" />Ends on {formatDate(offer.expires_at)}</p></div><section className="rounded-xl border border-slate-100 bg-slate-50 p-3"><Link href={businessHref} className="flex items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-brand-100 text-brand">{offer.business.thumbnail ? <img src={offer.business.thumbnail} alt="" className="size-full object-cover" /> : <i className="fa-solid fa-store" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-extrabold">{offer.business.name}</span><span className="mt-0.5 block truncate text-xs text-foreground-muted"><i className="fa-solid fa-location-dot mr-1 text-brand" />{address}</span></span><i className="fa-solid fa-chevron-right text-xs text-foreground-subtle" /></Link><div className="mt-3 grid grid-cols-3 gap-2"><BusinessAction href={business?.contact.phone ? `tel:${business.contact.phone}` : undefined} icon="fa-phone" label="Call" /><BusinessAction href={business?.contact.whatsapp ? `https://wa.me/${business.contact.whatsapp.replace(/\D/g, "")}` : undefined} icon="fa-whatsapp" label="WhatsApp" brand external /><BusinessAction href={directionsHref} icon="fa-diamond-turn-right" label="Direction" external /></div></section></article>;
}
function BusinessAction({ href, icon, label, brand = false, external = false }: { href?: string; icon: string; label: string; brand?: boolean; external?: boolean }) { const className = "flex h-9 min-w-0 items-center justify-center gap-1 rounded-lg border border-brand-200 bg-white px-1 text-[10px] font-extrabold text-brand disabled:border-slate-200 disabled:text-slate-300"; return href ? <a href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined} className={className}><i className={`${brand ? "fa-brands" : "fa-solid"} ${icon}`} /><span className="truncate">{label}</span></a> : <button type="button" disabled className={className}><i className={`${brand ? "fa-brands" : "fa-solid"} ${icon}`} /><span className="truncate">{label}</span></button>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(date); }
function OfferSkeleton() { return <div className="space-y-4">{[0, 1, 2].map((item) => <div key={item} className="h-64 animate-pulse rounded-2xl bg-white" />)}</div>; }
